name: Frontmatter Check
on:
  pull_request:
    paths: ["**/*.md"]
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Ensure YAML frontmatter exists
        run: |
          fail=0
          while IFS= read -r f; do
            # пропускаем README и .github
            case "$f" in
              ./README.md|.github/*) continue ;;
            esac
            # есть ли фронтматтер (--- в первой строке)
            if [ "$(head -n1 "$f")" != "---" ]; then
              echo "::error file=$f,line=1::Нет YAML-фронтматтера. Добавьте шаблон."
              fail=1
            fi
          done < <(git ls-files '**/*.md')
          exit $fail
